[tool.poetry]
name = "ftp"
version = "0.1.0"
description = ""
authors = ["Sagaidak <gith.num1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mypy = "^0.790"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
